# Generated by Django 4.2.1 on 2023-05-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
    ]
