# Generated by Django 4.2.1 on 2023-05-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='starts_in',
            field=models.DateTimeField(default=None, null=True, verbose_name='Campaign starts in'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='final_deadline',
            field=models.DateTimeField(default=None, null=True, verbose_name='Final Campaign deadline'),
        ),
    ]
