# Generated by Django 4.2.1 on 2023-05-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_starts_in_alter_campaign_final_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('CA', 'Canceled'), ('DE', 'Delivered'), ('WS', 'Waiting to Start'), ('NW', 'New')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='deliverables_drive_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='general_drive_url',
            field=models.URLField(default=''),
        ),
    ]
