# Generated by Django 4.2.1 on 2023-05-20 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0005_milestone_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('CA', 'Canceled'), ('DE', 'Delivered'), ('WS', 'Waiting to Start'), ('NW', 'New'), ('TP', 'Template Model')], default='NW', max_length=2),
        ),
    ]
