# Generated by Django 4.2.1 on 2023-05-20 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0006_campaign_team_milestone_team_task_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('CANCELED', 'Canceled'), ('DONE', 'Done'), ('WAITING', 'Waiting to Start'), ('NEW', 'New'), ('TEMPLATE', 'Template Model')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='UserTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('status', models.CharField(choices=[('CANCELED', 'Canceled'), ('TO DO', 'To do'), ('DOING', 'Doing'), ('DONE', 'Done')], default='TO DO', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(through='campaigns.UserTaskStatus', to=settings.AUTH_USER_MODEL),
        ),
    ]
