# Generated by Django 4.2.1 on 2023-05-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_users'),
        ('campaigns', '0009_rename_team_campaign_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='owner',
            field=models.ManyToManyField(null=True, to='teams.team'),
        ),
    ]
