# Generated by Django 4.2.1 on 2023-05-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaign_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Campain creation date'),
        ),
    ]
