# Generated by Django 4.2.1 on 2023-05-20 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('teams', '0003_team_users'),
        ('campaigns', '0011_alter_campaign_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('starts_in', models.DateTimeField(default=None, null=True, verbose_name='starts in')),
                ('final_deadline', models.DateTimeField(default=None, null=True, verbose_name='Final deadline')),
                ('general_drive_url', models.URLField(default='')),
                ('deliverables_drive_url', models.URLField(default='')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('CANCELED', 'Canceled'), ('DONE', 'Done'), ('WAITING', 'Waiting to Start'), ('NEW', 'New'), ('TEMPLATE', 'Template Model')], default='NEW', max_length=20)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
                ('owner', models.ManyToManyField(null=True, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.AddField(
            model_name='communicationdemand',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.communicationtype'),
        ),
    ]
