# Generated by Django 4.2.1 on 2023-05-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_communicationdemand_communicationtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='task',
            name='users',
        ),
        migrations.RemoveField(
            model_name='usertaskstatus',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertaskstatus',
            name='user',
        ),
        migrations.AddField(
            model_name='communicationdemand',
            name='requester_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Nome do solicitante'),
        ),
        migrations.AddField(
            model_name='communicationdemand',
            name='requester_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Nome do solicitante'),
        ),
        migrations.AddField(
            model_name='communicationdemand',
            name='requester_whatsapp',
            field=models.CharField(max_length=20, null=True, verbose_name='Whatsapp do solicitante'),
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='UserTaskStatus',
        ),
    ]
