# Generated by Django 4.2.1 on 2023-05-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_alter_communicationdemand_requester_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationdemand',
            name='organization_strategy',
            field=models.CharField(choices=[('HIGHT', 'Alta'), ('MEDIUM', 'Média'), ('LOW', 'Baixa'), ('UNDEFINED', 'Não definida')], default='UNDEFINED', max_length=10),
        ),
    ]
