# Generated by Django 4.2.1 on 2023-05-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_communicationdemand_organization_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationtype',
            name='color',
            field=models.CharField(default='999999', max_length=6),
        ),
    ]
