# Generated by Django 4.2.1 on 2023-05-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_communicationtype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtype',
            name='color',
            field=models.CharField(default='$999999', max_length=20),
        ),
    ]
