# Generated by Django 4.2.1 on 2023-05-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_communicationdemand_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationdemand',
            name='status',
            field=models.CharField(choices=[('CANCELED', 'Canceled'), ('DONE', 'Done'), ('WAITING', 'Waiting to Start'), ('NEW', 'New'), ('DOING', 'Executando'), ('TEMPLATE', 'Template Model')], default='NEW', max_length=20),
        ),
    ]
