# Generated by Django 4.2.1 on 2023-05-21 13:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0021_alter_communicationdemand_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Milestone',
            new_name='TaskGroup',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='milestone',
            new_name='task_group',
        ),
    ]
